    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / { try_files $uri $uri/ /index.html; }
        location /healthz {
            access_log off;
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }
        location /votes {

            proxy_pass http://vote-service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /vote {
            proxy_pass http://vote-service;
        }

        location /reset {
            proxy_pass http://vote-service;
        }
    }
